var cheerio = require('cheerio');
var request = require('request');
var melb = require('./app/scripts/melb_attendees.json');


// Remote DB
// var databaseUrl = "mongodb://admin:balognom123@ds049878.mongolab.com:49878/attendahh"; // "username:password@example.com/mydb"

// Local DB
var databaseUrl = "mydb"

var collections = ["domains"]

var db = require("mongojs").connect(databaseUrl, collections, {
    auto_reconnect: true,
    'poolSize': 50
});
var ObjectId = require("mongojs").ObjectId;


String.prototype.replaceBetween = function(start, end, what) {
    return this.substring(0, start) + what + this.substring(end);
};

var sydDoms = [ 'bitsandpieces.net.au',
  'yearntolearn.com.au',
  'designedbylife.com.au',
  'whereintheworldkp.com',
  'thechangestarter.com',
  'thewhiteagency.com.au',
  'holler.com.au',
  'deskspace.com.au',
  'mahlabmedia.com.au',
  'datarati.com.au',
  'adinajozsef.com.au',
  'curvychictours.com',
  'totalsynergy.com',
  'object.com.au',
  'extrablack.com.au',
  'mca.com.au',
  'mi9.com.au',
  'stemonline.com.au',
  'sydneylivingmuseums.com.au',
  'fadedempire.com.au',
  'thecooksgrocer.com.au',
  'wasamedia.com',
  'drawingbook.com.au',
  'funkis.com',
  'watsonsbayhotel.com.au',
  'alasthelabel.com',
  'intersect.org.au',
  'hcl.com',
  'brianritchie.me',
  'livewiremarkets.com',
  'milnealexander.com.au',
  'hflawyers.com.au',
  'culturalchameleon.com.au',
  'charliedehaas.com.au',
  'anmm.gov.au',
  'solzhouseshoes.com',
  'originagency.com.au',
  'theunspokenpitch.com',
  'goodsams.org.au',
  'redandblackzone.com',
  'savvyconsulting.com.au',
  'myrefinery.com.au',
  'samanthaball.com.au',
  'tapaas.com',
  'retail-x.com.au',
  'thefolk.com',
  'screenmyshorts.com',
  'nbnco.com.au',
  'bby.com.au',
  'macrovue.com.au',
  'epa.nsw.gov.au',
  'saramoss.com.au',
  'pulsemining.com.au',
  'lunchladylou.com',
  'wearesocial.net',
  'inceptiondigital.com.au',
  'tivoli2moro.com',
  'mashable.com',
  'ourgoldenage.com.au',
  'alfiesfriendrolfe.com.au',
  'retailoasis.com',
  'cooeeart.com.au',
  'zeusunwired.com',
  'perceptionz.net',
  'prezitraining.com.au',
  'traction-digital.com',
  'lafitte.com.au',
  '84thand3rd.com',
  'lgnsw.org.au',
  'monkeybaa.com.au',
  'nordicfusion.com.au',
  'edgecustom.com.au',
  'planetfurniture.com.au',
  'dearinassociates.com',
  'monpetitchou.com.au',
  'bellpotter.com.au',
  'clothfabric.com',
  'manofmany.com',
  'incubate.org.au',
  'nortonrosefulbright.com',
  'mensard.com',
  '8vamarketing.com.au',
  'photodoco.com',
  'riskresponse.com.au',
  'wholesome-cook.com',
  'meetoo.com.au',
  'thebeautyoflife.com.au',
  'fluffyjack.com',
  'kaleidoscopeblog.net',
  'taybenlor.com',
  'alexn.id.au',
  'zomt.com.au',
  'notoxbox.com.au',
  'theloverlist.com',
  'autumnproducts.com.au',
  'zefyrjewels.com.au',
  'suprios.com',
  'dynamic4.com',
  'lachstock.com.au',
  'ifyoubuildit.com.au',
  'nikigudex.com',
  'golflink.com.au',
  'zakrzewski.com.au',
  'mapwheel.com',
  'arbonpublishing.com',
  'worldacademy.tv',
  'redcross.org.au',
  'chada.com.au',
  'aboutmybrain.com',
  'darkcloudsilver.com',
  'surferliving.com',
  'percept.com.au',
  'razorfish.com.au',
  'benevolent.org.au',
  'mysticmedusa.com',
  'thecopycollective.com',
  'metroscreen.org.au',
  'and-sydney.com',
  'wholesale-blank-tshirts.com.au',
  'metal-roos.com.au',
  'setmyscene.com',
  'liveintheprojects.com',
  'miaudio.com',
  'interactiveideas.com.au',
  'vstarbliss.com',
  'thesparkinside.com',
  'createordie.com.au',
  'einterviewquestionsandanswers.com',
  'hsf.com',
  'personalisedfavours.com.au',
  'onlinemarketingworks.com.au',
  'getfancied.com',
  'defence.gov.au',
  'ss48.org',
  'hri.org.au',
  'andrewmaccoll.com',
  'servantofchaos.com',
  'canfixit.com.au',
  'modavanti.com',
  'visual.ly',
  'petsearch.com.au',
  'mattsharpe.com',
  'jasonmcdermott.net',
  'ppfinders.com.au',
  'aatkings.com.au',
  'banarra.com',
  'pushstart.com.au',
  'blueprintsolutionsgroup.com',
  'passionforlife.com.au',
  'sustainablebm.com.au',
  'storyberg.com',
  'artbuds.com',
  'hassellstudio.com',
  'stgeorgegraphics.com.au',
  'richardsison.com',
  'blacklemag.com',
  'bain.com',
  'broadreachservices.com',
  'frankteam.com.au',
  'ice.org.au',
  'sbs.com.au',
  'britishcouncil.org.au',
  'bohemiagroup.com.au',
  'spicyicecream.com.au',
  'sharethemess.com',
  'seanasmith.com',
  'joinwoo.com.au',
  '2datafish.com.au',
  'creditorwatch.com.au',
  'waywardson.com.au',
  'mitchellake.com',
  'yourtutor.com.au',
  'propellher.com',
  'inlite.com.au',
  'intersective.com',
  'sambag.com.au',
  'bauer-media.com.au',
  'theurbanmum.com.au',
  'lawpath.com.au',
  'valmont.com.au',
  'sacs.nsw.edu.au',
  'pega.com',
  'emilyvalentine.com.au',
  'redbubble.com',
  'sturt.nsw.edu.au',
  'spacefurniture.com.au',
  'agfarm.com.au',
  'winemarket.com.au',
  'mantragroup.com.au',
  'purestorage.com',
  'tksg.com.au',
  'koukii.com.au',
  'done.com.au',
  'burtonmetaldepository.com',
  'campaignmonitor.com',
  'exacttarget.com',
  'lonsec.com.au',
  '1am.co.nz',
  'cancer.org.au',
  'brookealexander.com.au',
  'cataloguemagazine.com.au',
  'hartldn.com',
  'gothat.com',
  'cassette.com.au',
  'walkleys.com',
  'sassandbide.com',
  'stylerunner.com',
  'gooddaygirl.com.au',
  'dreaminternship.com.au',
  'driveaway.com.au',
  'thebookkitchen.com.au',
  'thecorporatekid.com.au',
  'saxton.com.au',
  'rbgsyd.nsw.gov.au',
  'travelctm.com',
  'melon.com.au',
  'irresistiblelearning.com.au',
  'lomahstudios.com',
  'theiconic.com.au',
  'nelga.com',
  'pria.com.au',
  'dlux.org.au',
  'thepositivityinstitute.com.au',
  'careerone.com.au',
  'jets.com.au',
  'marxgrocer.com.au',
  'elitistcode.com',
  'atlassian.com',
  'vclass.com.au',
  'iconpark.com',
  'scribbleandthink.com',
  'muru-d.com',
  'planning.nsw.gov.au',
  'transfieldservices.com',
  'cirrusmedia.com.au',
  'ato.gov.au',
  'allens.com.au',
  'instrument-works.com',
  'amantalwar.com',
  'bassike.com',
  'intermediaconsulting.com.au',
  'employmentinnovations.com',
  'nannyshecando.com',
  'citrix.com',
  'nswcc.org.au',
  'steptwo.com.au',
  'goodman.com',
  'wellmovement.com',
  'wealthyandwise.com.au',
  'presentationstudio.com',
  'fotomerchant.com',
  'umusic.com',
  'stjohnnsw.com.au',
  'metail.co.uk',
  'elefanttraks.com',
  'lush.com.au',
  'aiad.com.au',
  'confidentliar.com',
  'moshtix.com.au',
  'wildbushluxury.com',
  'equilibriumdesign.com.au',
  'wisekangaroo.com',
  'moneysoft.com.au',
  'thisismango.com.au',
  'positionrealty.com.au',
  'thoughtspace.com.au',
  'stageandscreen.com.au',
  'thesaltbox.com.au',
  'businessinsider.com.au',
  'helpling.com',
  'campaignbug.com',
  'venturecrowd.com.au',
  'sproutinggood.com.au',
  'tradeignite.com',
  'eatfitfood.com.au',
  'clintsalter.com',
  'reinteractive.net',
  'hypedc.com',
  'slingshotters.com',
  'sweetdreamsdesigns.com',
  'computer.org',
  'a-positive.com.au',
  'hellobookcase.org',
  'grahamlea.com',
  'sweetstyle.com.au',
  'musicaviva.com.au',
  'mrplates.com',
  'volunteering.com.au',
  'reactive.com',
  'joebutton.com',
  'tpf.com.au',
  'esriaustralia.com.au',
  'matterdesign.com.au',
  'mattt.com.au',
  'bullseye-digital.com',
  'gadgets4geeks.com.au',
  'plchardware.com.au',
  'georgetown.edu',
  'amsrs.com.au',
  'deepspace.com.au',
  'cartercarter.com.au',
  'mobile-eye-clinic.com',
  'tripadvisor.com',
  'parkmyvan.com.au',
  'itwire.com',
  'stimulus.com.au',
  'rawideas.com',
  'fionacarter.com',
  'driva.com.au',
  'flash.com.au',
  'nari525.net',
  'qlc.io',
  'insatiablemunchies.com',
  'goodfuel.co',
  'landor.com',
  'livingedge.com.au',
  'mastermindconsulting.com.au',
  'aerios.com.au',
  'focalattractions.com.au',
  'dius.com.au',
  'monpurse.com',
  'benchpr.com.au',
  'brabhamgroup.com',
  'rippleffectgroup.com',
  '3rdsense.com',
  'zenithoptimedia.com.au',
  '89n.com',
  'webwise.com.au',
  'williamdejean.com',
  'arc.unsw.edu.au',
  'franklinwomen.com.au',
  'mychoicematters.org.au',
  'u1group.com',
  'futurespace.com.au',
  'viocorp.com',
  'littlefrenchy.com.au',
  'elements.net.au',
  'becfaye.com.au',
  'uncommonground.com.au',
  'workable.com',
  'trade.gov',
  'thesoundalliance.net',
  'pabloandrustys.com.au',
  'hudsonmeats.com',
  'backseat.me',
  'pollenizer.com',
  'hallchadwick.com.au',
  'promiseorpay.com',
  'cuttawayhillwines.com.au',
  'tallboysapparel.com',
  'soska.com.au',
  'swoon.com.au',
  'mybespokechair.com',
  'ccccnsw.org.au',
  'bilue.com.au',
  'scopemedia.com.au',
  'rga.com',
  'klick.com.au',
  'lightingmatters.com.au',
  'futureburo.com',
  'dublin.com',
  'worldtradeadvisors.com',
  'adshel.com.au',
  'blunt-instrument.com',
  'liveschool.net',
  'icur.com.au',
  'jevonsglobal.com',
  'dinosaurdistrict.com.au',
  'harrycourt.com',
  'thekindergroup.com',
  'cyborg.net.au',
  'fishburners.org',
  'agentbox.com.au',
  'digicomms.com.au',
  'luisabustos.com',
  'inscopemedia.com',
  'kidsatswitch.com.au',
  'getreadingright.com',
  'account-master.com',
  'mwebsolutions.com.au',
  'original-unverpackt.de',
  'someplace.com.au',
  'omnisoftware.com.au',
  'mapdataservices.com',
  'brandnewmedia.com.au',
  'recruitloop.com',
  'marketingjuice.com.au',
  'fromlittlethings.co',
  'clubbultaco.com.au',
  'thevirtualassistant.com.au',
  'doctours.com.au',
  'starlight.org.au',
  'analogfolk.com',
  'orchard.com.au',
  'choice.com.au',
  'vermilian.com',
  'fitnessnetwork.com.au',
  'marketboomer.com',
  'piip.org.au',
  'innuendoadvertising.com.au',
  'boiledeggsandsoldiers.com',
  'barnabyshop.com',
  'sizmek.com',
  'news.com.au',
  'thoughtworks.com',
  'dmg.com.au',
  'abc.net.au',
  'cityofsydney.nsw.gov.au',
  'unicef.org.au',
  'sparkk.com.au',
  'dizenya.com.au',
  'lovesdata.com',
  'thefarmdigital.com',
  'ecooutdoor.com.au',
  'cd.com.au',
  'lindatahija.com',
  'iquitsugar.com',
  'gbca.org.au',
  'h2coconut.com',
  'woollahra.nsw.gov.au',
  'fleetplus.com.au',
  'undergroupshowroom.com',
  'swaab.com.au',
  'resolutionmedia.com',
  'sklawyers.com.au',
  'analogfolk.com.au',
  'frankdigital.com.au',
  'lavender.ad',
  'persistentsys.com',
  'thegrindhouse.com',
  'getvero.com',
  'starz.com',
  'crowdsourcehire.com',
  'adinahotels.com.au',
  'reborn.com.au',
  'eq.com.au',
  'linkshare.com',
  'fourteendigital.com.au',
  'pwnetwork.com.au',
  'possumdigital.com.au',
  'newtonsnerds.com',
  'practiceignition.com',
  'inmobi.com',
  'hilton.com',
  'consumeraffairs.com',
  'northcott.com.au',
  'siroccohome.com.au',
  'ppca.com.au',
  'cambridgehotel.com.au',
  'concreteplayground.com.au',
  'racp.edu.au',
  'bloch.com.au',
  'circul8.com.au',
  'activehealthtech.com',
  'justsnacks.com.au',
  'realresultsmedia.com.au',
  'hotshotsactionevents.com',
  'jaswealth.com.au',
  'verbate.co',
  'fox.com',
  'kadocreative.com',
  'opencolleges.edu.au',
  'miamiadschool.com',
  'voxroxmedia.com',
  'jmc.edu.au',
  'zookal.com',
  'apnoutdoor.com.au',
  'snissan.me',
  'skillsapien.com',
  'baileystreetdesign.com.au',
  'orangebicycle.com.au',
  'yourmodern.co',
  'cellarmasters.com.au',
  'engagesciences.com',
  'viewsontop.com',
  'dnsw.com.au',
  'ssw.com.au',
  'thewebshowroom.com.au',
  'buzzfeed.com',
  'marsh.com',
  'ozforex.com.au',
  'trainingaidaustralia.com.au',
  'mccartneydesign.com.au',
  'presentationstudio.com.au',
  'momento.com.au',
  'hotcourses.com.au',
  'zdnet.com.au',
  'moomumedia.com',
  'webknowledgy.com.au',
  'joelspencerdesign.com',
  'stamfordinteractive.com.au',
  'dernovotny.com',
  'mooretechnology.com.au',
  'grays.com.au',
  'biblesociety.org.au',
  'hubaustralia.com',
  'theappvillage.com',
  'ozharvest.org',
  'kids.nsw.gov.au',
  'sponsorshipnews.com.au',
  'publicismojo.com.au',
  'lalalandshop.com.au',
  'tenthhouse.com.au',
  'yourhomeawayfromhome.com.au',
  'utsmotorsports.com',
  'australiandiabetescouncil.com',
  'enterprise-ireland.com',
  'ibest.com.br',
  'loveblackdresses.com.au',
  'novuscapital.com.au',
  'mrandmrsamos.com',
  'fusionbooks.com',
  'contactability.com.au',
  'jewishcare.com.au',
  'in.tum.de',
  'commercialisationaustralia.gov.au',
  'oragroup.com.au',
  'griffith.edu.au',
  'elsevier.com',
  'clintonpower.com.au',
  'besydney.com.au',
  'nps.org.au',
  'colourblocker.com',
  'magnoliasolutions.com.au',
  'viparo.com.au',
  'pleezpay.com',
  'saymac.com',
  'phanig.com',
  'codoc.org',
  'dexus.com',
  'circuitclub.com.au',
  'asx.com.au',
  'cubisteffects.com',
  'startupyard.cz',
  'alderip.com.au',
  'harleyjohnston.com',
  'chrisharold.com',
  'apcgenius.com',
  'neboengineering.com.au',
  'smokeball.com',
  'firstclickconsulting.com',
  'acpmagazines.com.au',
  'alkhabeer.com',
  'wagen.com.au',
  'findpoker.com.au',
  'olsenorringe.com',
  'anchor.com.au',
  'contexti.com',
  'icssydney.com',
  'ambition.com.au',
  'duomo.com.au',
  'razorfishhealthware.com.au',
  'helenkaminski.com',
  'acya.org.au',
  'medobs.com.au',
  'the-hub.net',
  'ccia.org.au',
  'lx-group.com.au',
  'austrade.gov.au',
  'kdigital.com.au',
  'conciergeconnections.com.au',
  'iflyflat.com.au',
  'caradvice.com.au',
  'homedesigndirectory.com.au',
  'collaborativeconsumption.com',
  'thefetch.org',
  'andy.me',
  'aussiewinetv.com',
  'xoox.com.au',
  'salesforce.com',
  'urbanwalkabout.com',
  'artfairsaustralia.com.au',
  'directcouriers.com.au',
  'irmau.com',
  'amadeus.com',
  'oracle.com',
  'mynrma.com.au',
  'okane.com.au',
  'foogi.me',
  'objectivedigital.com',
  'servcorp.com.au',
  'tapestry.net',
  'brrmedia.com',
  'accenture.com',
  'btopenworld.com',
  'vistaprint.com',
  'lakerepublic.com',
  'charteredaccountants.com.au',
  'qantas.com.au',
  'schneider-electric.com',
  'ellaslist.com.au',
  'newsdigitalmedia.com.au',
  'feedbackloop.com.au',
  'thefarmdigital.com.au',
  'buyreply.com',
  'maketonightcount.com',
  'thefashionninja.com',
  'ginevra.org',
  'rodemic.com',
  'oxfam.org.au',
  'etsy.com',
  'fourpillarsgin.com.au',
  'ppbadvisory.com',
  'tfehotels.com',
  'handkrafted.com',
  'zmail.unsw.edu.au',
  'cloudsherpas.com',
  'getup.org.au',
  'shiztastic.com',
  'myhealthjourney.com',
  'digitalninjas.com',
  'nettfunder.com',
  'glamazonapp.com',
  'rallydev.com',
  'theguardian.com',
  'redballoon.com.au',
  'sydneyoperahouse.com',
  'lead2work.com',
  'write-here.org',
  'australianbusiness.com.au'
  ];

var melDoms = [ 
  'futuremusicgroup.com.au']

var twits = [];

function lookUp(url, soc){
//	console.log("looking up " + url);

	request('http://' + url, function (error, response, html) {
	
	  if (!error && response.statusCode == 200) {
	    var $ = cheerio.load(html);
      
      if(!soc){

  	    var m = $('div:contains("mailing list")').length;
  	    var m2 = $('div:contains("Mailing list")').length;
  	    var m3 = $('div:contains("Mailing List")').length;
  	    var m4 = $('div:contains("MAILING LIST")').length;
  	    var m5 = $('div:contains("subscribe")').length;
  	    var m6 = $('div:contains("Subscribe")').length;
  	    var m7 = $('div:contains("SUBSCRIBE")').length;
  	    var m8 = $('div:contains("newsletter")').length;
  	    var m9 = $('div:contains("Newsletter")').length;
  	    var m10 = $('div:contains("NEWSLETTER")').length;

  	    if (m > 0|| m2 > 0 || m3 > 0 || m4 > 0 || m5 > 0 || m6 > 0 || m7 > 0 || m8 > 0 || m9 > 0 || m10 > 0){
  	    	console.log(url + " - They have a mailing list!");
  	    	melDoms.push(url);
  	    	console.log(melDoms);
  	    }
      }else if(soc === 'twit'){
        var twit = $("a[href*='twitter\.com']").attr('href');
        if(twit){
          if((twit.indexOf('search?') == -1) && (twit.indexOf('intent/') == -1) && (twit.indexOf('share?') == -1) && (twit.indexOf('/home') == -1) ){
            var j = twit.replaceBetween(0,twit.indexOf('twitter.com/'),"http://").replaceBetween(0,twit.indexOf('twitter.com/'),"https://")
            var k = j.replace('#!/', '');
            
            request(k, function (error, response, html) {
              if (!error && response.statusCode == 200) {
                var d = cheerio.load(html);

                var f = d('.ProfileNav-item.ProfileNav-item--followers span.ProfileNav-value').text().replace(',','');

                if (f.indexOf('.') !== -1){
                  var followers = f.replace('.','').replace('M','0000').replace('K', '00');
                }else{
                  var followers = f.replace('K', '000');
                }

                var tempObj = {domain: url, twitter: k, followers: parseInt(followers)};
                twits.push(tempObj);
                console.log(tempObj);
              }else{
                console.log("ERR with " + k, error, response.statusCode);
              }
            });
          }
        }else{
        //  console.log(url + " didn't have a twitter link");
        }

      }else if(soc === 'fb'){
        var fb = $("a[href*=facebook]").attr('href');

        if(fb){
          request(twit, function (error, response, html) {
            var d = cheerio.load(html);

            var fans = d('._50f5').text().replace(' likes','');
            console.log(url + ": Facebook Fans:", fans);
          });
        }else{
          console.log(url + " didn't have an FB link");
        }

      }
	  }
	});
}


function doList(list){
	for (var key in list){
		var found = 0;
		for (var i = 0; i<melDoms.length; i++){
			if(melDoms[i] === key){
				found++;
				console.log("found " + key + " in melDoms");
			}
			if((i === melDoms.length -1) && found === 0){
			lookUp(key);
			}
		
		}
	}
}


//doList(melb[0]);

function findTwit(list){
  console.log(list.length);
  for (var i = 0; i<list.length; i++){
    lookUp(list[i], 'twit');
  }
}

 findTwit(melDoms);

//
//for (var j = 0; j<twits.length; j++){
//  request(twits[j], function (error, response, html) {
//    if (!error && response.statusCode == 200) {
//      var d = cheerio.load(html);
//      var followers = d('.ProfileNav-item.ProfileNav-item--followers span.ProfileNav-value').text();
//      console.log(twits[j] + ": Twitter Followers:", followers);
//    }else{
//      console.log("ERR", error, response.statusCode);
//    }
//  });
//}